GET http://localhost:5218/games

GET http://localhost:5218/games/2


POST http://localhost:5218/games
Content-Type: application/json

{
    "name": "Final Fantasy XIV",
    "genreId": 2,
    "price": 59.99,
    "releaseDate": "2010-09-30"
}